unit10/config/routes.rb
Rails.application.routes.draw do
  resources :selected_pets

  resources :carts

  resources :pets
  resources :shelter

  root 'shelter#index'

end

unit10/app/models/cart.rb
class Cart < ActiveRecord::Base
  has_many :selected_pets, dependent: :destroy
end

unit10/app/models/pet.rb
class Pet < ActiveRecord::Base
	has_many :selected_pets
	before_destroy :ensure_not_selected
	enum pet_type: [ :dog, :cat ]
	validates :name, presence: true
	validates :description, length: { in: 10..40 }

	def is_selected
		self.update(Pet_Status: "Selected")
	end

	def not_selected
		self.update(Pet_Status: "Available")
	end

	private

	def ensure_not_selected
		if selected_pets.empty?
			return true
		else
			errors.add(:base, 'Pet has already been selected')
			return false
		end
	end
end

unit10/app/models/selected_pet.rb
class SelectedPet < ActiveRecord::Base
  belongs_to :pet
  belongs_to :cart
end

unit10/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

unit10/app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: [:show, :edit, :update, :destroy]

  rescue_from ActiveRecord::RecordNotFound, with: :invalid_cart

  def invalid_cart
    logger.error "Attempt to access invalid cart #{params[:id]}"
    redirect_to shelter_index_url, notice: 'Invalid cart'
  end

  # GET /carts
  # GET /carts.json
  def index
    @carts = Cart.all
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1
  # PATCH/PUT /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart.destroy
    respond_to do |format|
      format.html { redirect_to carts_url, notice: 'Cart was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cart_params
      params[:cart]
    end
end

unit10/app/controllers/concerns/current_cart.rb
require 'active_support/concern'

module CurrentCart
  extend ActiveSupport::Concern

#  private
   def set_cart
    @cart = Cart.find(session[:cart_id])
  rescue ActiveRecord::RecordNotFound
    @cart = Cart.create
    session[:cart_id] = @cart.id
   end

end

unit10/app/controllers/pets_controller.rb
class PetsController < ApplicationController
  before_action :set_pet, only: [:show, :edit, :update, :destroy]

  # GET /pets
  # GET /pets.json
  def index
    @pets = Pet.all
  end

  # GET /pets/1
  # GET /pets/1.json
  def show
  end

  # GET /pets/new
  def new
    @pet = Pet.new
  end

  # GET /pets/1/edit
  def edit
  end

  # POST /pets
  # POST /pets.json
  def create
    @pet = Pet.new(pet_params)
    @pet.not_selected
    respond_to do |format|
      if @pet.save
        format.html { redirect_to @pet, notice: 'Pet was successfully created.' }
        format.json { render :show, status: :created, location: @pet }
      else
        format.html { render :new }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pets/1
  # PATCH/PUT /pets/1.json
  def update
    respond_to do |format|
      if @pet.update(pet_params)
        format.html { redirect_to @pet, notice: 'Pet was successfully updated.' }
        format.json { render :show, status: :ok, location: @pet }
      else
        format.html { render :edit }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pets/1
  # DELETE /pets/1.json
  def destroy
    @pet.destroy
    respond_to do |format|
      format.html { redirect_to pets_url, notice: 'Pet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pet
      @pet = Pet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pet_params
      params.require(:pet).permit(:name, :age, :description, :pet_type, :pet_status)
    end
end

unit10/app/controllers/selected_pets_controller.rb
class SelectedPetsController < ApplicationController
  include CurrentCart
  before_action :set_cart, only: [:create]
  before_action :set_selected_pet, only: [:show, :edit, :update, :destroy]

  # GET /selected_pets
  # GET /selected_pets.json
  def index
    @selected_pets = SelectedPet.all
  end

  # GET /selected_pets/1
  # GET /selected_pets/1.json
  def show
  end

  # GET /selected_pets/new
  def new
    @selected_pet = SelectedPet.new
  end

  # GET /selected_pets/1/edit
  def edit
  end

  # POST /selected_pets
  # POST /selected_pets.json
  def create
    pet = Pet.find(params[:pet_id])
    @selected_pet = @cart.selected_pets.build(pet: pet)
    pet.is_selected
    respond_to do |format|
      if @selected_pet.save
        format.html { redirect_to @selected_pet.cart, notice: 'Pet was selected' }
        #format.html { redirect_to @selected_pet, notice: 'Selected pet was successfully created.' }
        format.json { render :show, status: :created, location: @selected_pet }
      else
        format.html { render :new }
        format.json { render json: @selected_pet.errors, status: :unprocessable_entity }
      end
    end

  end

  # PATCH/PUT /selected_pets/1
  # PATCH/PUT /selected_pets/1.json
  def update
    respond_to do |format|
      if @selected_pet.update(selected_pet_params)
        format.html { redirect_to @selected_pet, notice: 'Selected pet was successfully updated.' }
        format.json { render :show, status: :ok, location: @selected_pet }
      else
        format.html { render :edit }
        format.json { render json: @selected_pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /selected_pets/1
  # DELETE /selected_pets/1.json
  def destroy
    pet = Pet.find(@selected_pet.pet_id)
    pet.not_selected
    @selected_pet.destroy
    respond_to do |format|
      format.html { redirect_to :controller => 'shelter', :action => 'index'}
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_selected_pet
      @selected_pet = SelectedPet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def selected_pet_params
      #params.require(:selected_pet).permit(:pet_id)
      params.require(:selected_pet).permit(:pet_id)
    end
end

unit10/app/controllers/shelter_controller.rb
class ShelterController < ApplicationController
  include CurrentCart
  before_action only: [:create]


  def index
    @pets = Pet.all.order(pet_type: :asc)
    #set_cart
    #@pets = Pet.where(Pet_Status == "Available")
  end

end

unit10/app/helpers/application_helper.rb
module ApplicationHelper
end

unit10/app/helpers/carts_helper.rb
module CartsHelper
end

unit10/app/helpers/pets_helper.rb
module PetsHelper
end

unit10/app/helpers/selected_pets_helper.rb
module SelectedPetsHelper
end

unit10/app/helpers/shelter_helper.rb
module ShelterHelper
end

unit10/app/views/pets/_form.html.erb
<%= form_for(@pet) do |f| %>
  <% if @pet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pet.errors.count, "error") %> prohibited this pet from being saved:</h2>

      <ul>
      <% @pet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
	<div class="field">
		<%= f.label :type %><br>
		<%= f.select :pet_type, options_for_select(Pet.pet_types.map {|k,v| [k,k]})	%>
	</div>
  <div class="field">
    <%= f.label :age %><br>
    <%= f.text_field :age %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description, :size => 40%>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

unit10/app/views/pets/edit.html.erb
<h1>Editing Pet</h1>

<%= render 'form' %>

<%= link_to 'Show', @pet %> |
<%= link_to 'Back', pets_path %>

unit10/app/views/pets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Pets</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Age</th>
      <th>Description</th>
			<th>Type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pets.each do |pet| %>
      <tr>
        <td><%= pet.name %></td>
        <td><%= pet.age %></td>
        <td><%= pet.description %></td>
				<td><%= pet.pet_type %></td>
        <td><%= link_to 'Show', pet %></td>
        <td><%= link_to 'Edit', edit_pet_path(pet) %></td>
        <td><%= link_to 'Destroy', pet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pet', new_pet_path %>

unit10/app/views/pets/new.html.erb
<h1>New Pet</h1>

<%= render 'form' %>

<%= link_to 'Back', pets_path %>

unit10/app/views/pets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @pet.name %>
</p>

<p>
  <strong>Age:</strong>
  <%= @pet.age %>
</p>

<p>
  <strong>Description:</strong>
  <%= @pet.description %>
</p>

<%= link_to 'Edit', edit_pet_path(@pet) %> |
<%= link_to 'Back', pets_path %>

unit10/app/views/shelter/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Pets</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Age</th>
      <th>Description</th>
      <th>Type</th>
      <th>Status</th>
    </tr>
  </thead>

  <tbody>
    <% @pets.each do |pet| %>
      <tr>
        <td><%= pet.name %></td>
        <td><%= pet.age %></td>
        <td><%= pet.description %></td>
        <td><%= pet.pet_type %></td>
        <td><%= pet.Pet_Status %></td>
        <td><%= button_to 'Select Pet', selected_pets_path(pet_id: pet) %></td>
       </tr>
    <% end %>
  </tbody>
</table>

<br>