unit05/config/routes.rb
Rails.application.routes.draw do
  resources :stores

  resources :computers, :stores

  resources :stores do
    resources :computers
  end
end

unit05/app/models/book.rb
class Book < ActiveRecord::Base
end

unit05/app/models/computer.rb
require_relative 'store'
class Computer < ActiveRecord::Base
  belongs_to :store
validates :brand, presence: true, length: { minimum: 1 }
validates :price, presence: true
validates :screen_size, numericality: {greater_than: 1}
  validates :cpu, numericality: true, inclusion: { in: [1,2,4,6,8]}
end

unit05/app/models/store.rb
class Store < ActiveRecord::Base
  has_many :computers, dependent: :destroy
end

unit05/app/controllers/computers_controller.rb
class ComputersController < ApplicationController
  before_action :set_computer, only: [:show, :edit, :update, :destroy]

  # GET /computers
  # GET /computers.json
  def index
    @computers = Computer.all
  end

  # GET /computers/1
  # GET /computers/1.json
  def show
  end

  # GET /computers/new
  def new
    @computer = Computer.new
  end

  # GET /computers/1/edit
  def edit
  end

  # POST /computers
  # POST /computers.json
  def create
    @store = Store.find(params[:store_id])
    @computer = @store.computers.create(computer_params)
    redirect_to computer_path(@store)

    respond_to do |format|
      if @computer.save
        format.html { redirect_to @computer, notice: 'Computer was successfully created.' }
        format.json { render :show, status: :created, location: @computer }
      else
        format.html { render :new }
        format.json { render json: @computer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /computers/1
  # PATCH/PUT /computers/1.json
  def update
    respond_to do |format|
      if @computer.update(computer_params)
        format.html { redirect_to @computer, notice: 'Computer was successfully updated.' }
        format.json { render :show, status: :ok, location: @computer }
      else
        format.html { render :edit }
        format.json { render json: @computer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /computers/1
  # DELETE /computers/1.json
  def destroy
    @store = Store.find(params[:store_id])
    @computer = @store.computers.find(params[:id])
    @computer.destroy
    redirect_to computer_path(@store)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_computer
      @computer = Computer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def computer_params
      params.require(:computer).permit(:brand, :price, :screen_size, :cpu)
    end
end

unit05/app/controllers/stores_controller.rb
class StoresController < ApplicationController
  before_action :set_store, only: [:show, :edit, :update, :destroy]

  # GET /stores
  # GET /stores.json
  def index
    @stores = Store.all
  end

  # GET /stores/1
  # GET /stores/1.json
  def show
  end

  # GET /stores/new
  def new
    @store = Store.new
  end

  # GET /stores/1/edit
  def edit
  end

  # POST /stores
  # POST /stores.json
  def create
    @store = Store.new(store_params)

    respond_to do |format|
      if @store.save
        format.html { redirect_to @store, notice: 'Store was successfully created.' }
        format.json { render :show, status: :created, location: @store }
      else
        format.html { render :new }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stores/1
  # PATCH/PUT /stores/1.json
  def update
    respond_to do |format|
      if @store.update(store_params)
        format.html { redirect_to @store, notice: 'Store was successfully updated.' }
        format.json { render :show, status: :ok, location: @store }
      else
        format.html { render :edit }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stores/1
  # DELETE /stores/1.json
  def destroy
    @store.destroy
    respond_to do |format|
      format.html { redirect_to stores_url, notice: 'Store was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_store
      @store = Store.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def store_params
      params.require(:store).permit(:name, :city)
    end
end

unit05/app/helpers/computers_helper.rb
module ComputersHelper
end

unit05/app/helpers/stores_helper.rb
module StoresHelper
end

unit05/app/views/computers/_form.html.erb
<%= form_for(@computer) do |f| %>
  <% if @computer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@computer.errors.count, "error") %> prohibited this computer from being saved:</h2>

      <ul>
      <% @computer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :brand %><br>
    <%= f.text_field :brand %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :screen_size %><br>
    <%= f.number_field :screen_size %>
  </div>
	  <div class="field">
    <%= f.label :cpu %><br>
    <%= f.number_field :cpu %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

unit05/app/views/computers/edit.html.erb
<h1>Editing Computer</h1>

<%= render 'form' %>

<%= link_to 'Show', @computer %> |
<%= link_to 'Back', computers_path %>

unit05/app/views/computers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Computers</h1>

<table>
  <thead>
    <tr>
      <th>Brand</th>
      <th>Price</th>
      <th>Screen size</th>
			<th>CPU</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @computers.each do |computer| %>
      <tr>
        <td><%= computer.brand %></td>
        <td><%= computer.price %></td>
        <td><%= computer.screen_size %></td>
				<td><%= computer.cpu %></td>
        <td><%= link_to 'Show', computer %></td>
        <td><%= link_to 'Edit', edit_computer_path(computer) %></td>
        <td><%= link_to 'Destroy', computer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Computer', new_computer_path %>

unit05/app/views/computers/new.html.erb
<h1>New Computer</h1>

<%= render 'form' %>

<%= link_to 'Back', computers_path %>

unit05/app/views/computers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Brand:</strong>
  <%= @computer.brand %>
</p>

<p>
  <strong>Price:</strong>
  <%= @computer.price %>
</p>

<p>
  <strong>Screen size:</strong>
  <%= @computer.screen_size %>
</p>

<p>
	<strong>CPU:</strong>
	<%= @computer.cpu %>
</p>

<%= link_to 'Edit', edit_computer_path(@computer) %> |
<%= link_to 'Back', computers_path %>

unit05/app/views/stores/_form.html.erb
<%= form_for(@store) do |f| %>
  <% if @store.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@store.errors.count, "error") %> prohibited this store from being saved:</h2>

      <ul>
      <% @store.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

unit05/app/views/stores/edit.html.erb
<h1>Editing Store</h1>

<%= render 'form' %>

<%= link_to 'Show', @store %> |
<%= link_to 'Back', stores_path %>

unit05/app/views/stores/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Stores</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>City</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @stores.each do |store| %>
      <tr>
        <td><%= store.name %></td>
        <td><%= store.city %></td>
        <td><%= link_to 'Show', store %></td>
        <td><%= link_to 'Edit', edit_store_path(store) %></td>
        <td><%= link_to 'Destroy', store, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Store', new_store_path %>

unit05/app/views/stores/new.html.erb
<h1>New Store</h1>

<%= render 'form' %>

<%= link_to 'Back', stores_path %>

unit05/app/views/stores/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @store.name %>
</p>

<p>
  <strong>City:</strong>
  <%= @store.city %>
</p>

<h2>Computers</h2>
<% @store.computers.each do |computer| %>

      <strong>Brand:</strong>
      <%= computer.brand %>

      Price:
      <%= computer.price %>

      Screen Size:
      <%= computer.screen_size %>

      CPU Cores
      <%= computer.cpu %>

    <%= link_to 'Edit', edit_computer_path(computer) %> |
      <%= link_to 'Delete', [computer.store, computer],
                  method: :delete,
                  data: { confirm: 'Are you sure?' } %>
<% end %>

<br>
<%= link_to 'Edit', edit_store_path(@store) %> |
<%= link_to 'Back', stores_path %>